In [1]:
import numpy as np

# pandas DataFrame out of NumPy arrays

In [2]:
# This is to examplify how NumPy is the backbone of many other libraries.
import pandas as pd
df = pd.DataFrame(np.random.randint(55555, size=(8,5)), columns =['a','b','c','d','e'])
df

a      b      c      d      e
0  16159  49874  42716  50176   8563
1  51910   6880  42134  28786  26894
2  21302  50550  50964  40065  32478
3  51071   6881  52008  47143  51036
4  13433  25171   5019  51643  42287
5  14340  43352  42311  10649  43477
6  49390  35474    130  51070   7773
7  16700  42411  44057  54897  39555

In [3]:
a1 = np.array([1,2,3])

a2 = np.array([[1,2.0,3],
              [4,5,6]])

a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])

In [4]:
a2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [5]:
a2a = pd.DataFrame(a2)
a2a

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.0

In [6]:
type(a2)

numpy.ndarray

## 2. Creating arrays

* `np.array()`
* `np.ones()`
* `np.zeros()`
* `np.random.rand(5, 3)`
* `np.random.randint(10, size=5)`
* `np.random.seed()` - pseudo random numbers
* Searching the documentation example (finding `np.unique()` and using it)

In [7]:
c_a1 = np.array([1,5,7,5])
c_a1, c_a1.dtype

(array([1, 5, 7, 5]), dtype('int32'))

In [8]:
c_a1 = np.array((1,5,7,5))
c_a1, c_a1.dtype

(array([1, 5, 7, 5]), dtype('int32'))

In [9]:
# Create an array of ones
ones = np.ones((10,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
# # The default datatype is 'float64'
ones.dtype

dtype('float64')

* `You can change the datatype with .astype()`

In [11]:
ones.astype(int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [12]:
# Create an array of zeros
zeros = np.zeros((5,3,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
zeros.dtype

dtype('float64')

In [16]:
# Create an array within a range of value
#                 Sart - Stop - Step
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [21]:
# Random array
ran_array = np.random.random((5,3))
ran_array

array([[0.12658548, 0.23678886, 0.20775867],
       [0.76866745, 0.60577227, 0.31199018],
       [0.45292006, 0.37982402, 0.10952777],
       [0.37895809, 0.96415868, 0.58312999],
       [0.54413012, 0.05733172, 0.15224365]])